redunduncy & path navigation

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -30,7 +30,16 @@ jobs:
 
     steps:
       - uses: actions/checkout@v4
-
+      - name: Navigate to project folder
+        run: |
+          cd springboot-swagger-crud || { echo "Error: Project folder not found"; exit 1; }
+          echo "PROJECT_DIR=$(pwd)" >> $GITHUB_ENV
+          JAR_FILE=$(ls target/ | grep -E '^springboot-swagger-crud.*\.jar$')
+          if [ -z "$JAR_FILE" ]; then
+            echo "Error: No JAR file found in target/"
+            exit 1
+          fi
+          echo "JAR_FILE=target/$JAR_FILE" >> $GITHUB_ENV
       - name: Setup Java 17
         uses: actions/setup-java@v4
         with:
