redunduncy & path navigation12

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -33,7 +33,7 @@ jobs:
 
       - name: Navigate to project folder
         run: |
-          cd springboot-swagger-crud/springboot-swagger-crud || { echo "Error: Project folder not found"; exit 1; }
+          cd springboot-swagger-crud || { echo "Error: Project folder not found"; exit 1; }
           echo "PROJECT_DIR=$(pwd)" >> $GITHUB_ENV
           JAR_FILE=$(ls target/ | grep -E '^springboot-swagger-crud.*\.jar$' | head -1)
           if [ -z "$JAR_FILE" ]; then
