fixing CD and CI works again

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -33,14 +33,10 @@ jobs:
 
       - name: Navigate to project folder
         run: |
-          cd springboot-swagger-crud || { echo "Error: Project folder not found"; exit 1; }
+          cd springboot-swagger-crud/springboot-swagger-crud || { echo "Error: Project folder not found"; exit 1; }
           echo "PROJECT_DIR=$(pwd)" >> $GITHUB_ENV
           JAR_FILE=$(ls target/ | grep -E '^springboot-swagger-crud.*\.jar$' | head -1)
-          if [ -z "$JAR_FILE" ]; then
-            echo "JAR_FILE=target/springboot-swagger-crud.jar" >> $GITHUB_ENV
-          else
-            echo "JAR_FILE=target/$JAR_FILE" >> $GITHUB_ENV
-          fi
+          echo "JAR_FILE=target/$JAR_FILE" >> $GITHUB_ENV
 
       - name: Setup JDK 17
         uses: actions/setup-java@v3
@@ -63,11 +59,12 @@ jobs:
         run: chmod +x mvnw && ./mvnw clean verify
 
       - name: Upload Artifacts
+        working-directory: ${{ env.PROJECT_DIR }}
         uses: actions/upload-artifact@v4
         with:
           name: springboot-app-artifacts
           path: |
-            ${{ env.PROJECT_DIR }}/target/*.jar
-            ${{ env.PROJECT_DIR }}/Dockerfile
-            ${{ env.PROJECT_DIR }}/src/main/resources/db/changelog/**
+            target/*.jar
+            Dockerfile
+            src/main/resources/db/changelog/**
           retention-days: 1
